apiVersion: apps/v1
kind: Deployment
metadata:
  name: sim-backend-dev
  namespace: sim-backend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sim
  template:
    metadata:
      labels:
        app: sim
    spec:
      containers:
        - name: sim-backend-container
          image: 212845026981.dkr.ecr.eu-central-1.amazonaws.com/sim-backend-dev:0.0.84-4299d7787a3c4250dc89540ccdde3817e2f454a0-0.50.15
          ports:
            - name: sim-port
              containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://*:8080"